name: musicme
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ^3.5.2


dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  permission_handler: ^11.3.1
  smooth_page_indicator: ^1.2.0+3
  shared_preferences: ^2.3.4
  salomon_bottom_bar: ^3.3.2
  url_launcher: ^6.3.1
  on_audio_query: ^2.9.0
  hive: ^2.2.3
  hive_generator: ^2.0.1
  hive_flutter: ^1.1.0
  just_audio: ^0.9.42
  popover: ^0.3.1
  uuid: ^4.5.1
  just_audio_background: ^0.0.1-beta.13
  fluttertoast: ^8.2.10
  marquee_text: ^2.5.0+1
  flutter_marquee: ^2.0.1
  rename: ^3.0.2
  
# To dev dependecyies are menioned below.............

dev_dependencies:
  flutter_test:
    sdk: flutter

 
  flutter_lints: ^4.0.0
  build_runner: ^2.4.13
  flutter_launcher_icons: ^0.14.2
flutter_icons: 
  image_path: "assets/image/musicmelogo.png"
  android: true
  ios: true
  min_sdk_android: 21 # android min sdk min:16, default 21
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/image/musicmelogo.png"


flutter:


  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/image/
    - assets/vector/
    


  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: inter
  #     fonts:
  #       - asset: asset/font/Inter_28pt-Bold.ttf
  #         style: normal
  #         weight: 700
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
